################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_FILES += "..\0_Src\4_McHal\Tricore\Scu\Std\IfxScuCcu.c"
OBJ_FILES += "0_Src\4_McHal\Tricore\Scu\Std\IfxScuCcu.o"
"0_Src\4_McHal\Tricore\Scu\Std\IfxScuCcu.o" : "..\0_Src\4_McHal\Tricore\Scu\Std\IfxScuCcu.c" "0_Src\4_McHal\Tricore\Scu\Std\.IfxScuCcu.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "0_Src\4_McHal\Tricore\Scu\Std\.IfxScuCcu.o.opt"

"0_Src\4_McHal\Tricore\Scu\Std\.IfxScuCcu.o.opt" : .refresh
	@argfile "0_Src\4_McHal\Tricore\Scu\Std\.IfxScuCcu.o.opt" -o "0_Src\4_McHal\Tricore\Scu\Std\IfxScuCcu.o" "..\0_Src\4_McHal\Tricore\Scu\Std\IfxScuCcu.c" -Ctc27xc --lsl-core=vtc -t -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC" -Wa-H"sfr/regtc27xc.def" -Wa-gAHLs --emit-locals=-equs,-symbols -Wa-Ogs -Wa--error-limit=42 -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Config\Common" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\2_CDrv\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Tricore\Main" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\If" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\StdIf" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\SysSe" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\Tricore\Compilers" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Impl" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Lib" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_PinMap" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Reg" --iso=99 --language=-gcc,-volatile,+strings,-kanji --fp-model=clfznrST --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O2 --tradeoff=4 --compact-max-size=200 -g --error-limit=42 --source -c --dep-file="0_Src\4_McHal\Tricore\Scu\Std\.IfxScuCcu.o.d" -Wc--make-target="0_Src\4_McHal\Tricore\Scu\Std\IfxScuCcu.o"
DEPENDENCY_FILES += "0_Src\4_McHal\Tricore\Scu\Std\.IfxScuCcu.o.d"

C_FILES += "..\0_Src\4_McHal\Tricore\Scu\Std\IfxScuEru.c"
OBJ_FILES += "0_Src\4_McHal\Tricore\Scu\Std\IfxScuEru.o"
"0_Src\4_McHal\Tricore\Scu\Std\IfxScuEru.o" : "..\0_Src\4_McHal\Tricore\Scu\Std\IfxScuEru.c" "0_Src\4_McHal\Tricore\Scu\Std\.IfxScuEru.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "0_Src\4_McHal\Tricore\Scu\Std\.IfxScuEru.o.opt"

"0_Src\4_McHal\Tricore\Scu\Std\.IfxScuEru.o.opt" : .refresh
	@argfile "0_Src\4_McHal\Tricore\Scu\Std\.IfxScuEru.o.opt" -o "0_Src\4_McHal\Tricore\Scu\Std\IfxScuEru.o" "..\0_Src\4_McHal\Tricore\Scu\Std\IfxScuEru.c" -Ctc27xc --lsl-core=vtc -t -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC" -Wa-H"sfr/regtc27xc.def" -Wa-gAHLs --emit-locals=-equs,-symbols -Wa-Ogs -Wa--error-limit=42 -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Config\Common" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\2_CDrv\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Tricore\Main" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\If" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\StdIf" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\SysSe" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\Tricore\Compilers" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Impl" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Lib" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_PinMap" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Reg" --iso=99 --language=-gcc,-volatile,+strings,-kanji --fp-model=clfznrST --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O2 --tradeoff=4 --compact-max-size=200 -g --error-limit=42 --source -c --dep-file="0_Src\4_McHal\Tricore\Scu\Std\.IfxScuEru.o.d" -Wc--make-target="0_Src\4_McHal\Tricore\Scu\Std\IfxScuEru.o"
DEPENDENCY_FILES += "0_Src\4_McHal\Tricore\Scu\Std\.IfxScuEru.o.d"

C_FILES += "..\0_Src\4_McHal\Tricore\Scu\Std\IfxScuWdt.c"
OBJ_FILES += "0_Src\4_McHal\Tricore\Scu\Std\IfxScuWdt.o"
"0_Src\4_McHal\Tricore\Scu\Std\IfxScuWdt.o" : "..\0_Src\4_McHal\Tricore\Scu\Std\IfxScuWdt.c" "0_Src\4_McHal\Tricore\Scu\Std\.IfxScuWdt.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "0_Src\4_McHal\Tricore\Scu\Std\.IfxScuWdt.o.opt"

"0_Src\4_McHal\Tricore\Scu\Std\.IfxScuWdt.o.opt" : .refresh
	@argfile "0_Src\4_McHal\Tricore\Scu\Std\.IfxScuWdt.o.opt" -o "0_Src\4_McHal\Tricore\Scu\Std\IfxScuWdt.o" "..\0_Src\4_McHal\Tricore\Scu\Std\IfxScuWdt.c" -Ctc27xc --lsl-core=vtc -t -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC" -Wa-H"sfr/regtc27xc.def" -Wa-gAHLs --emit-locals=-equs,-symbols -Wa-Ogs -Wa--error-limit=42 -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Config\Common" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\2_CDrv\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Tricore\Main" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\If" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\StdIf" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\SysSe" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\Tricore\Compilers" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Impl" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Lib" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_PinMap" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Reg" --iso=99 --language=-gcc,-volatile,+strings,-kanji --fp-model=clfznrST --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O2 --tradeoff=4 --compact-max-size=200 -g --error-limit=42 --source -c --dep-file="0_Src\4_McHal\Tricore\Scu\Std\.IfxScuWdt.o.d" -Wc--make-target="0_Src\4_McHal\Tricore\Scu\Std\IfxScuWdt.o"
DEPENDENCY_FILES += "0_Src\4_McHal\Tricore\Scu\Std\.IfxScuWdt.o.d"


GENERATED_FILES += "0_Src\4_McHal\Tricore\Scu\Std\IfxScuCcu.o" "0_Src\4_McHal\Tricore\Scu\Std\.IfxScuCcu.o.opt" "0_Src\4_McHal\Tricore\Scu\Std\.IfxScuCcu.o.d" "0_Src\4_McHal\Tricore\Scu\Std\IfxScuCcu.src" "0_Src\4_McHal\Tricore\Scu\Std\IfxScuCcu.lst" "0_Src\4_McHal\Tricore\Scu\Std\IfxScuEru.o" "0_Src\4_McHal\Tricore\Scu\Std\.IfxScuEru.o.opt" "0_Src\4_McHal\Tricore\Scu\Std\.IfxScuEru.o.d" "0_Src\4_McHal\Tricore\Scu\Std\IfxScuEru.src" "0_Src\4_McHal\Tricore\Scu\Std\IfxScuEru.lst" "0_Src\4_McHal\Tricore\Scu\Std\IfxScuWdt.o" "0_Src\4_McHal\Tricore\Scu\Std\.IfxScuWdt.o.opt" "0_Src\4_McHal\Tricore\Scu\Std\.IfxScuWdt.o.d" "0_Src\4_McHal\Tricore\Scu\Std\IfxScuWdt.src" "0_Src\4_McHal\Tricore\Scu\Std\IfxScuWdt.lst"
