################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_FILES += "..\0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart0.c"
OBJ_FILES += "0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart0.o"
"0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart0.o" : "..\0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart0.c" "0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart0.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart0.o.opt"

"0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart0.o.opt" : .refresh
	@argfile "0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart0.o.opt" -o "0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart0.o" "..\0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart0.c" -Ctc27xc --lsl-core=vtc -t -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC" -Wa-H"sfr/regtc27xc.def" -Wa-gAHLs --emit-locals=-equs,-symbols -Wa-Ogs -Wa--error-limit=42 -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Config\Common" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\2_CDrv\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Tricore\Main" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\If" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\StdIf" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\SysSe" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\Tricore\Compilers" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Impl" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Lib" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_PinMap" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Reg" --iso=99 --language=-gcc,-volatile,+strings,-kanji --fp-model=clfznrST --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O2 --tradeoff=4 --compact-max-size=200 -g --error-limit=42 --source -c --dep-file="0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart0.o.d" -Wc--make-target="0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart0.o"
DEPENDENCY_FILES += "0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart0.o.d"

C_FILES += "..\0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart1.c"
OBJ_FILES += "0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart1.o"
"0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart1.o" : "..\0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart1.c" "0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart1.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart1.o.opt"

"0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart1.o.opt" : .refresh
	@argfile "0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart1.o.opt" -o "0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart1.o" "..\0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart1.c" -Ctc27xc --lsl-core=vtc -t -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC" -Wa-H"sfr/regtc27xc.def" -Wa-gAHLs --emit-locals=-equs,-symbols -Wa-Ogs -Wa--error-limit=42 -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Config\Common" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\2_CDrv\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Tricore\Main" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\If" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\StdIf" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\SysSe" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\Tricore\Compilers" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Impl" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Lib" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_PinMap" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Reg" --iso=99 --language=-gcc,-volatile,+strings,-kanji --fp-model=clfznrST --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O2 --tradeoff=4 --compact-max-size=200 -g --error-limit=42 --source -c --dep-file="0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart1.o.d" -Wc--make-target="0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart1.o"
DEPENDENCY_FILES += "0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart1.o.d"

C_FILES += "..\0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart2.c"
OBJ_FILES += "0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart2.o"
"0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart2.o" : "..\0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart2.c" "0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart2.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart2.o.opt"

"0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart2.o.opt" : .refresh
	@argfile "0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart2.o.opt" -o "0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart2.o" "..\0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart2.c" -Ctc27xc --lsl-core=vtc -t -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC" -Wa-H"sfr/regtc27xc.def" -Wa-gAHLs --emit-locals=-equs,-symbols -Wa-Ogs -Wa--error-limit=42 -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Config\Common" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\2_CDrv\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Tricore\Main" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\If" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\StdIf" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\SysSe" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\Tricore\Compilers" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Impl" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Lib" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_PinMap" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Reg" --iso=99 --language=-gcc,-volatile,+strings,-kanji --fp-model=clfznrST --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O2 --tradeoff=4 --compact-max-size=200 -g --error-limit=42 --source -c --dep-file="0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart2.o.d" -Wc--make-target="0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart2.o"
DEPENDENCY_FILES += "0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart2.o.d"


GENERATED_FILES += "0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart0.o" "0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart0.o.opt" "0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart0.o.d" "0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart0.src" "0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart0.lst" "0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart1.o" "0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart1.o.opt" "0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart1.o.d" "0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart1.src" "0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart1.lst" "0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart2.o" "0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart2.o.opt" "0_Src\4_McHal\Tricore\Cpu\CStart\.IfxCpu_CStart2.o.d" "0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart2.src" "0_Src\4_McHal\Tricore\Cpu\CStart\IfxCpu_CStart2.lst"
