################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_FILES += "..\0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.asm.c"
OBJ_FILES += "0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.asm.o"
"0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.asm.o" : "..\0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.asm.c" "0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_CircularBuffer.asm.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_CircularBuffer.asm.o.opt"

"0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_CircularBuffer.asm.o.opt" : .refresh
	@argfile "0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_CircularBuffer.asm.o.opt" -o "0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.asm.o" "..\0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.asm.c" -Ctc27xc --lsl-core=vtc -t -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC" -Wa-H"sfr/regtc27xc.def" -Wa-gAHLs --emit-locals=-equs,-symbols -Wa-Ogs -Wa--error-limit=42 -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Config\Common" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\2_CDrv\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Tricore\Main" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\If" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\StdIf" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\SysSe" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\Tricore\Compilers" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Impl" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Lib" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_PinMap" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Reg" --iso=99 --language=-gcc,-volatile,+strings,-kanji --fp-model=clfznrST --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O2 --tradeoff=4 --compact-max-size=200 -g --error-limit=42 --source -c --dep-file="0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_CircularBuffer.asm.o.d" -Wc--make-target="0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.asm.o"
DEPENDENCY_FILES += "0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_CircularBuffer.asm.o.d"

C_FILES += "..\0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.c"
OBJ_FILES += "0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.o"
"0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.o" : "..\0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.c" "0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_CircularBuffer.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_CircularBuffer.o.opt"

"0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_CircularBuffer.o.opt" : .refresh
	@argfile "0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_CircularBuffer.o.opt" -o "0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.o" "..\0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.c" -Ctc27xc --lsl-core=vtc -t -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC" -Wa-H"sfr/regtc27xc.def" -Wa-gAHLs --emit-locals=-equs,-symbols -Wa-Ogs -Wa--error-limit=42 -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Config\Common" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\2_CDrv\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Tricore\Main" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\If" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\StdIf" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\SysSe" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\Tricore\Compilers" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Impl" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Lib" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_PinMap" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Reg" --iso=99 --language=-gcc,-volatile,+strings,-kanji --fp-model=clfznrST --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O2 --tradeoff=4 --compact-max-size=200 -g --error-limit=42 --source -c --dep-file="0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_CircularBuffer.o.d" -Wc--make-target="0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.o"
DEPENDENCY_FILES += "0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_CircularBuffer.o.d"

C_FILES += "..\0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_Fifo.c"
OBJ_FILES += "0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_Fifo.o"
"0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_Fifo.o" : "..\0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_Fifo.c" "0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_Fifo.o.opt"
	@echo Compiling ${<F}
	@"${PRODDIR}\bin\cctc" -f "0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_Fifo.o.opt"

"0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_Fifo.o.opt" : .refresh
	@argfile "0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_Fifo.o.opt" -o "0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_Fifo.o" "..\0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_Fifo.c" -Ctc27xc --lsl-core=vtc -t -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC" -Wa-H"sfr/regtc27xc.def" -Wa-gAHLs --emit-locals=-equs,-symbols -Wa-Ogs -Wa--error-limit=42 -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Config\Common" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\2_CDrv\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\0_AppSw\Tricore\Main" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\If" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\StdIf" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\SysSe" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\1_SrvSw\Tricore\Compilers" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Impl" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Lib" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_PinMap" -I"D:\WorkSpace\Tasking\Tasking_TC27xD_ASC\0_Src\4_McHal\Tricore\_Reg" --iso=99 --language=-gcc,-volatile,+strings,-kanji --fp-model=clfznrST --switch=auto --align=0 --default-near-size=8 --default-a0-size=0 --default-a1-size=0 -O2 --tradeoff=4 --compact-max-size=200 -g --error-limit=42 --source -c --dep-file="0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_Fifo.o.d" -Wc--make-target="0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_Fifo.o"
DEPENDENCY_FILES += "0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_Fifo.o.d"


GENERATED_FILES += "0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.asm.o" "0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_CircularBuffer.asm.o.opt" "0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_CircularBuffer.asm.o.d" "0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.asm.src" "0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.asm.lst" "0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.o" "0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_CircularBuffer.o.opt" "0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_CircularBuffer.o.d" "0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.src" "0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_CircularBuffer.lst" "0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_Fifo.o" "0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_Fifo.o.opt" "0_Src\4_McHal\Tricore\_Lib\DataHandling\.Ifx_Fifo.o.d" "0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_Fifo.src" "0_Src\4_McHal\Tricore\_Lib\DataHandling\Ifx_Fifo.lst"
